name: andrewdw-ski-app
region: lon

services:
    - name: ceros-test
      dockerfile_path: Dockerfile
      source_dir: /
      github:
          branch: main
          deploy_on_push: true
          repo: andrewdw/ceros-test
      http_port: 8080
      instance_count: 1
      instance_size_slug: basic-xxs
      health_check:
          http_path: /
          initial_delay_seconds: 10
      envs:
          - key: PORT
            value: "8080"
