version: '3.8'

services:
  ski:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ski
    environment:
      - NODE_ENV=production
    ports:
      - '8080:8080'
    restart: unless-stopped
